SELECT
	Fname, Lname
FROM DEPARTMENT
JOIN EMPLOYEE
ON DEPARTMENT.Mgr_ssn=EMPLOYEE.Ssn
WHERE Dname='Research';

SELECT
	Fname, Lname
FROM PROJECT
JOIN EMPLOYEE ON PROJECT.Dnum=EMPLOYEE.Dno
WHERE Pname='Newbenefits';

SELECT
	Dependent_name
FROM DEPENDENT
JOIN EMPLOYEE
ON EMPLOYEE.Ssn=DEPENDENT.Essn
WHERE Fname='Franklin' AND Lname='Wong';

SELECT
	Dependent_name
FROM DEPENDENT
JOIN EMPLOYEE
ON DEPENDENT.Essn=EMPLOYEE.Ssn
JOIN PROJECT
ON PROJECT.Dnum=EMPLOYEE.Dno
WHERE Pname='Computerization';

SELECT
	Dname
FROM DEPARTMENT
JOIN EMPLOYEE
ON DEPARTMENT.Dnumber=EMPLOYEE.Dno
JOIN DEPENDENT
ON DEPENDENT.Essn=EMPLOYEE.Ssn
WHERE Relationship='Son';